### ISSUE TITLE
TiDB helm chart?

### ISSUE THREAD

**Issue by F21** [iamxy/tidb-on-k8s#1]
Since this repo already allows you to run TiDB on k8s, you might be interested in submitting it to https://github.com/kubernetes/charts

kubernetes/charts is sort of like a package repository (think apt-get or yum) for k8s. Using the kubernetes/helm tool, you can easily install things like postgres, redis, etc into a k8s cluster. I think TiDB would be a pretty good fit!

**Comment by shenli** [comment]
@F21 Thanks for your suggestion. We will consider it.

**Comment by grugnog** [comment]
I like this idea also - even if it is not full production ready right off the bat, it would make it easy to try it out.
